# Settings: https://yamllint.readthedocs.io/en/stable/

extends: default

yaml-files:
  - "*.yaml"
  - "*.yml"

rules:
  line-length: {max: 500}
  document-start: disable
  braces:
    min-spaces-inside: 0
    max-spaces-inside: 1
  indentation:
    spaces: 2
  comments:
    min-spaces-from-content: 1
  comments-indentation: disable
