services:
  minio:
    image: minio/minio:RELEASE.2025-04-22T22-12-26Z
    container_name: minio
    ports:
      - "9000:9000" # API S3 compatible
      - "9001:9001" # Console Web UI
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server --console-address ":9001" /data
    volumes:
      - ${MINIO_DATA_DIR}:/data
  dagster:
    build:
      context: ./../..
      dockerfile: infra/docker/Dockerfile
    image: dagster-app:latest
    container_name: dagster
    ports:
      - "3000:3000"
    depends_on:
      - minio
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - ./:/app
    command: ["dagster", "dev"]
