apiVersion: v1
kind: Service
metadata:
  name: minio-external
  namespace: dagster
spec:
  type: ExternalName
  externalName: host.k3d.internal # ⬅️ or host.docker.internal / 192.168.X.X
  ports:
    - port: 9000
      targetPort: 9000
